# Site settings
author: Trevor Tarpinian
title: Codology
header-img: img/home-bg.png
email: tmtarpinian@gmail.com
copyright_name: Trevor Tarpinian
description: > # this means to ignore newlines until "baseurl:"
  Career Changer Learning Ruby, Rails, Front End, SQL, React
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ferrisbueller66

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
